### ISSUE TITLE
Unable to display the name of an area

### ISSUE THREAD

**Issue by ikkentim** [OsmSharp/OsmSharp#218]
I would like to be able to display the name of an area, but it just doesn't display it..

``` css
area[name] {
    text-color: black;
    text-halo-radius: 2;
    text-halo-color: white;
    font-size: 14;
    /*text: name;*/ /*not working with or without*/
}
```
![](http://www.quick-screen.co.uk/5xtc35)
